name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner environment

    steps:
      - name: Checkout code  # Checkout the code repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx  # Set up Docker Buildx for multi-platform builds
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub  # Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image  # Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .  # Use the current directory as context for the build
          push: true  # Push the Docker image to Docker Hub
          tags: sarahuo/my-flask:latest  # Tag the Docker image

